### ISSUE TITLE
Moving the Realtek drivers

### ISSUE THREAD

**Issue by kimocoder** [acai66/op6-op6t-nethunter-kernel#1]
Hi again!

Do you mind moving the Realtek drivers into "drivers/net/wireless/realtek" ? Then we'll add the support to our other kernels (like OP7T) by simply moving only the folder :+1: 

And is it okey we use your kernel as the official one for OP6 in NetHunter? Best regards

**Comment by kimocoder** [comment]
Thanks @acai66 -- really appreciate it :1st_place_medal:

**Comment by acai66** [comment]
> Hi again!
> 
> Do you mind moving the Realtek drivers into "drivers/net/wireless/realtek" ? Then we'll add the support to our other kernels (like OP7T) by simply moving only the folder +1
> 
> And is it okey we use your kernel as the official one for OP6 in NetHunter? Best regards

It have been moved, it's okey

**Comment by kimocoder** [comment]
Did you fix the HID btw? @re4son seems to have the solution for newer kernels :+1:

**Comment by acai66** [comment]
> Did you fix the HID btw? @Re4son seems to have the solution for newer kernels +1

i will try

**Comment by kimocoder** [comment]
We'll help you get it done before going into the NetHunter installer, no worries :+1:

**Comment by acai66** [comment]
HID gadget patch has been applied, and it still needs  to run `setprop sys.usb.config win,hid` first.

**Comment by Re4son** [comment]
Awesome job. Thanks!
We are working on a menu in the NetHunter app to query the /init.nethunter.rc file for all supported modes and list them in a spinner. The user can choose one and activate it.
Have you tested your init.nethunter.rc file? Is it copying any discriptor files across? We had to disable the copying on newer devices as it comes with its own vendor provided descriptors and it would cause boot loops

Many thanks,
Re4son

**Comment by acai66** [comment]
> Awesome job. Thanks!
> We are working on a menu in the NetHunter app to query the /init.nethunter.rc file for all supported modes and list them in a spinner. The user can choose one and activate it.
> Have you tested your init.nethunter.rc file? Is it copying any discriptor files across? We had to disable the copying on newer devices as it comes with its own vendor provided descriptors and it would cause boot loops
> 
> Many thanks,
> Re4son

i'm looking forward to new Nethunter APP, thanks for your great efforts. 
I tested, only mouse works well now, keyboard not works.

**Comment by kimocoder** [comment]
Awesome. We'll get it working all together, NetHunter APP is moving forward too

**Comment by acai66** [comment]
HID has been fixed, no copy descriptors.
