### ISSUE TITLE
Before we add it to NetHunter

### ISSUE THREAD

**Issue by kimocoder** [acai66/op6-op6t-nethunter-kernel#2]
There is one issue with the kernel, we're ready ro push it to NetHunter with your credits, but the xbin folder with the "bootkali" scripts will destroy our setup as we used updated ones that's not released. The files is included/updated by the APK. We Will make the files available for xbin too shortly, so the works in "adb shell". 

We're ready when your ready

**Comment by acai66** [comment]
ok, i will remove them soon
